;;; vc-check-status-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vc-check-status.el

(defvar vc-check nil "\
Buffer-local variable that defines the list of states to
check.")
(make-variable-buffer-local 'vc-check)
(put 'vc-check 'safe-local-variable 'vc-check-safe-p)
(autoload 'vc-check-status-activate "vc-check-status" "\


(fn &optional ARG)" t)
(register-definition-prefixes "vc-check-status" '("mapconcatend" "vc-check-"))


;;; Generated autoloads from vc-git-check-status.el

(register-definition-prefixes "vc-git-check-status" '("vc-git-"))

;;; End of scraped data

(provide 'vc-check-status-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vc-check-status-autoloads.el ends here
