;;; lang.el --- Tree-sitter 与 LSP (eglot) -*- lexical-binding: t -*-

;; Grammar 名须与内置 ts-mode 一致（如 C# 为 c-sharp，不是 csharp）。
;; 使用 URL + 分支 + 源码子目录，便于 `M-x treesit-install-language-grammar' 与各版本 Emacs 兼容。
(setq treesit-language-source-alist
      '((bash "https://github.com/tree-sitter/tree-sitter-bash" "master" "src")
        (c "https://github.com/tree-sitter/tree-sitter-c" "master" "src")
        (cpp "https://github.com/tree-sitter/tree-sitter-cpp" "master" "src")
        (cmake "https://github.com/uyha/tree-sitter-cmake" "master" "src")
        (css "https://github.com/tree-sitter/tree-sitter-css" "master" "src")
        (c-sharp "https://github.com/tree-sitter/tree-sitter-c-sharp" "master" "src")
        (dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile" "master" "src")
        (doxygen "https://github.com/tree-sitter-grammars/tree-sitter-doxygen" "master" "src")
        (elixir "https://github.com/elixir-lang/tree-sitter-elixir" "main" "src")
        (heex "https://github.com/phoenixframework/tree-sitter-heex" "main" "src")
        (go "https://github.com/tree-sitter/tree-sitter-go" "master" "src")
        (gomod "https://github.com/camdencheek/tree-sitter-go-mod" "master" "src")
        (gowork "https://github.com/omertuc/tree-sitter-go-work" "master" "src")
        (html "https://github.com/tree-sitter/tree-sitter-html" "master" "src")
        (java "https://github.com/tree-sitter/tree-sitter-java" "master" "src")
        (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
        (jsdoc "https://github.com/tree-sitter/tree-sitter-jsdoc" "master" "src")
        (json "https://github.com/tree-sitter/tree-sitter-json" "master" "src")
        (lua "https://github.com/tree-sitter-grammars/tree-sitter-lua" "master" "src")
        (php "https://github.com/tree-sitter/tree-sitter-php" "master" "php/src")
        (phpdoc "https://github.com/claytonrcarter/tree-sitter-phpdoc" "master" "src")
        (python "https://github.com/tree-sitter/tree-sitter-python" "master" "src")
        (ruby "https://github.com/tree-sitter/tree-sitter-ruby" "master" "src")
        (rust "https://github.com/tree-sitter/tree-sitter-rust" "master" "src")
        (toml "https://github.com/tree-sitter-grammars/tree-sitter-toml" "master" "src")
        (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
        (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
        (yaml "https://github.com/tree-sitter-grammars/tree-sitter-yaml" "master" "src")))

(setq major-mode-remap-alist
      (append
       '((c-mode . c-ts-mode)
         (c++-mode . c++-ts-mode)
         (c-or-c++-mode . c-or-c++-ts-mode)
         (sh-mode . bash-ts-mode)
         (python-mode . python-ts-mode)
         (ruby-mode . ruby-ts-mode)
         (rust-mode . rust-ts-mode)
         (go-mode . go-ts-mode)
         (go-mod-mode . go-mod-ts-mode)
         (go-work-mode . go-work-ts-mode)
         (java-mode . java-ts-mode)
         (csharp-mode . csharp-ts-mode)
         (js-mode . js-ts-mode)
         (typescript-mode . typescript-ts-mode)
         (tsx-mode . tsx-ts-mode)
         (js-json-mode . json-ts-mode)
         (json-mode . json-ts-mode)
         (css-mode . css-ts-mode)
         (yaml-mode . yaml-ts-mode)
         (php-mode . php-ts-mode)
         (lua-mode . lua-ts-mode)
         (dockerfile-mode . dockerfile-ts-mode)
         (cmake-mode . cmake-ts-mode)
         (elixir-mode . elixir-ts-mode)
         (conf-toml-mode . toml-ts-mode))
       (when (fboundp 'mhtml-ts-mode)
         '((mhtml-mode . mhtml-ts-mode)))))

(use-package eglot
  :config
  (add-hook 'python-mode-hook 'eglot-ensure)
  (add-hook 'rust-mode-hook 'eglot-ensure)
  (add-hook 'typescript-ts-mode-hook 'eglot-ensure)
  (add-hook 'scheme-mode-hook 'eglot-ensure))
